### ISSUE TITLE
No "copy-part-of-file" targets found.

### ISSUE THREAD

**Issue by mike1011** [dehru/grunt-copy-part-of-file#6]
i have added copy part of file module and added as it is given in the readme.

Wondering what creating this error.

```
    //copy now added in gruntfile
      copy_part_of_file: {
          simple_replace_scripts: {
              options: {
                  sourceFileStartPattern: '<!-- SIMPLE START -->',
                  sourceFileEndPattern: '<!-- SIMPLE END -->',
                  destinationFileStartPattern: '<!-- START -->',
                  destinationFileEndPattern: '<!-- END -->'
              },
              files: {
                  'src/sample.html': ['src/final.html']
              }
          }
      },    

```
src folder also has both `sample` and `final`.html files.`sample.html` is filled by html markups each having the `<!-- SIMPLE START -->.<!-- SIMPLE END-->,<!-- START -->`  and `<!-- END -->` comments.

Error coming on git bash
```
$ grunt copy_part_of_file
Warning: Task "copy_part_of_file" not found. Use --force to continue.


```

package.json

`"grunt-copy-part-of-file": "^0.1.5",`

node_modules also have `grunt-copy-part-of-file` folder

**Comment by dehru** [comment]
Did you add this at the top of your Gruntfile.js?

grunt.loadNpmTasks('grunt-copy-part-of-file');

**Comment by dehru** [comment]
Ah, I see the README has underscores instead of dashes.  Thanks for the issue.  I've updated the readme.  Implement your task like this, notice the quotes around the task key because of the dashes:

```
grunt.initConfig({
  'copy-part-of-file': {
      simple_replace_scripts: {
          options: {
              sourceFileStartPattern: '<!-- SIMPLE START -->',
              sourceFileEndPattern: '<!-- SIMPLE END -->',
              destinationFileStartPattern: '<!-- START -->',
              destinationFileEndPattern: '<!-- END -->'
          },
          files: {
              'test/fixtures/simple-destination.html': ['test/fixtures/simple-source.html']
          }
      }
  },
})
```
then you should be able to just run:
```
grunt copy-part-of-file
```

Let me know if that resolves it.  I've switched to gulp/webpack lately.

**Comment by mike1011** [comment]
Thanks @dehru ,i have updated my grunt task,now the task the running but complaining for `file not found`.

```
$ grunt copy-part-of-file
Running "copy-part-of-file:simple_replace_scripts" (copy-part-of-file) task
>> Source file f not found.
File "sample.html" created.

Done, without errors.

```



```
//copy now
     'copy-part-of-file': {
          simple_replace_scripts: {
              options: {
                  sourceFileStartPattern: '<!-- SIMPLE START -->',
                  sourceFileEndPattern: '<!-- SIMPLE END -->',
                  destinationFileStartPattern: '<!-- START -->',
                  destinationFileEndPattern: '<!-- END -->'
              },
              files: {
                 //they both are present in root folder
                  'sample.html': ['final.html']
              }
          }
      },  
```
```
**final.html**
<!-- This is where we copy the file content using markup text -->

<div id="here_comes_the_copied_text">
<!-- START -->

<!-- END -->
</div>
```


**sample.html - with any random position to test whether copy is working**
```
<!-- SIMPLE START -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

<!-- SIMPLE END -->
```

Am i missing something. ?

**Comment by dehru** [comment]
Notice that in my example, the sample file is on the right and the destination file is on the left.  This is weird but it's how grunt does it.  So i think you'd need to change it to.
```
'final.html': ['sample.html']
```
Are you on Mac or Windows?  You could also try './final.html':['./sample.html'] if that doesn't work.  Let me know if you get success.

**Comment by mike1011** [comment]
Yeah...this got worked...Thanks @dehru  for your help.

**Comment by mike1011** [comment]
why i am unable to copy head section of a html file already present in my root folder.is it possible to copy any part of markup from already existing file.

```
'copy-part-of-file': {
        simple_replace_scripts: {
            options: {
                sourceFileStartPattern: '<head>',
                sourceFileEndPattern: ' </head> ',
                destinationFileStartPattern: '<head>',
                destinationFileEndPattern: '</head>'
            },
            files: {
                'new_file.html': ['new.html']
            }
        }
    }
```

i get this warning,when i try the above command, even if both the files are present where new.html is prefilled file and new_file is blank

$ grunt copy-part-of-file
Running "copy-part-of-file:simple_replace_scripts" (copy-part-of-file) task
>> Source file b not found.
>> You must provide a destination file, destination start pattern, and destination end pattern.
Warning: You must provide a destination file, destination start pattern, and destination end pattern. Use --force to continue.
